# Generated by Django 5.0.1 on 2024-02-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_musician_email_remove_musician_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='user',
        ),
        migrations.AddField(
            model_name='musician',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
